[project]
name = "get-ktec-smt-schedule"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cookiecutter>=2.6.0",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "pytest>=8.4.2",
    "pyxlsb>=1.0.10",
    "setuptools>=80.9.0",
    "styleframe>=4.2",
    "wheel>=0.45.1",
    "xlrd>=2.0.2",
]
